FROM node:12-alpine as builder
WORKDIR /app
COPY package.json /app/package.json
RUN npm install --only=prod
COPY . /app
RUN npm run build
FROM nginx:1.16.0-alpine
COPY --from=build /build dev.lct.40ants.com:/var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]